"""Blob storage interface.

Keys are POSIX-style relative paths generated by the app (never by users), e.g.
``assets/tts/tts-ab12.../Xk3...q.mp3`` (public, served from /media) or
``private/source/source-cd34.../Pq9...z.pdf`` (never served). ``put_*`` never overwrites an
existing object: callers always write to fresh unique keys.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Protocol, runtime_checkable

_SEGMENT_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_\-]*(\.[A-Za-z0-9]+)*")
_WINDOWS_RESERVED = {"con", "prn", "aux", "nul", *(f"com{i}" for i in range(1, 10)), *(f"lpt{i}" for i in range(1, 10))}
MAX_SEGMENTS = 8


def validate_key(key: str) -> str:
    """Strictly validate a storage key (raises ValueError)."""
    if not isinstance(key, str) or not key or len(key) > 500:
        raise ValueError("invalid storage key")
    parts = key.split("/")
    if len(parts) > MAX_SEGMENTS:
        raise ValueError("storage key has too many segments")
    for p in parts:
        if not _SEGMENT_RE.fullmatch(p):
            raise ValueError(f"invalid storage key segment {p!r}")
        if p.split(".")[0].lower() in _WINDOWS_RESERVED:
            raise ValueError(f"reserved name in storage key: {p!r}")
    return key


def is_public_key(key: str) -> bool:
    return key.startswith("assets/")


@runtime_checkable
class Storage(Protocol):
    name: str

    def put_bytes(self, key: str, data: bytes, content_type: str) -> None: ...

    def put_file(self, key: str, path: Path, content_type: str) -> None: ...

    def get_bytes(self, key: str) -> bytes: ...

    def download_to(self, key: str, path: Path) -> Path:
        """Copy the object to a local path (used by ffmpeg/manim). Returns ``path``."""
        ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...

    def size(self, key: str) -> int: ...

    def public_url(self, key: str) -> str:
        """Stable, non-expiring URL (local: ``/media/<key>``; s3: CDN base + key). Safe to cache."""
        ...

    def signed_url(self, key: str, ttl_seconds: int, *, download_name: str | None = None) -> str:
        """Short-lived URL generated at serve time (s3 presigned GET; local: same as public_url)."""
        ...

    def local_path(self, key: str) -> Path | None:
        """Filesystem path for the local backend; None for remote backends."""
        ...
