// Browser check of Visual Review (review.js + POST /api/visuals/review) in real Chrome, against a
// separate, throwaway server whose AI providers are a local stand-in (AI_FAKE_PROVIDER=1): no real
// provider can be reached and the normal database, library and media folders are never touched.
//
//   1. initial review: every scene visual listed, pending, nothing generated by opening the review
//   2. Keep -> approved, still approved after a reload
//   3. Change -> Asset Library (found by its description) -> changed, same asset after a reload
//   4. Remove -> no visual, still removed after a reload
//   5. AI cache: "Generate AI video" makes the planned video once; the same request again is a
//      cache hit (same asset, no provider call)
//   6. "Generate new AI version": a new asset, exactly one provider call, the old asset kept
//   7. export: the recording shows the reviewed visuals (the chosen clip, verified in the file's
//      pixels), the removed scene has none and nothing more is generated
//
// Needs Chrome, ffmpeg, playwright-core (npm install --no-save playwright-core, or PLAYWRIGHT_CORE_DIR)
// and the repo's virtualenv (.venv). Uses the default admin login of a fresh database:
//   AADHI_PASSWORD=... node tests/visual_review_browser_check.mjs
// Silent: no audio output, browser speech stubbed, narration answered with silence, the captured
// tab's sound not played locally.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT = process.env.REVIEW_CHECK_OUT || path.join(os.tmpdir(), 'aadhi-review-check');
const PASSWORD = process.env.AADHI_PASSWORD;
const PORT = Number(process.env.REVIEW_CHECK_PORT || 9910 + (process.pid % 30));
const BASE = `http://127.0.0.1:${PORT}`;
if (!PASSWORD) {
    console.error('Set AADHI_PASSWORD to the default admin password (a fresh database creates that admin).');
    process.exit(2);
}

const results = [];
function check(name, ok, detail = '') {
    results.push({ name, ok: !!ok, detail });
    console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? '  (' + detail + ')' : ''}`);
}

async function loadPlaywright() {
    try {
        return await import('playwright-core');
    } catch (e) {
        if (process.env.PLAYWRIGHT_CORE_DIR) return import(pathToFileURL(path.join(process.env.PLAYWRIGHT_CORE_DIR, 'index.mjs')).href);
        throw new Error('playwright-core not found: run `npm install --no-save playwright-core` (or set PLAYWRIGHT_CORE_DIR)');
    }
}

function run(cmd, args) {
    const r = spawnSync(cmd, args, { encoding: 'utf8', maxBuffer: 1 << 26 });
    if (r.status !== 0) throw new Error(`${cmd} failed: ${r.stderr}`);
    return r;
}

// ---- a throwaway server with the stand-in AI providers ------------------------------------------
fs.rmSync(OUT, { recursive: true, force: true });
const data = path.join(OUT, 'server-data');
for (const dir of ['assets', 'exports', 'static']) fs.mkdirSync(path.join(data, dir), { recursive: true });
const venvScripts = path.join(REPO, '.venv', process.platform === 'win32' ? 'Scripts' : 'bin');
const serverLog = fs.openSync(path.join(OUT, 'server.log'), 'w');
const server = spawn(path.join(venvScripts, process.platform === 'win32' ? 'python.exe' : 'python'),
    ['-m', 'uvicorn', 'server:app', '--host', '127.0.0.1', '--port', String(PORT)], {
        cwd: REPO,
        stdio: ['ignore', serverLog, serverLog],
        env: {
            ...process.env,
            PATH: venvScripts + path.delimiter + process.env.PATH,
            DATABASE_URL: 'sqlite:///' + path.join(data, 'check.db').replace(/\\/g, '/'),
            ASSETS_DIR: path.join(data, 'assets'),
            EXPORTS_DIR: path.join(data, 'exports'),
            STATIC_DIR: path.join(data, 'static'),
            JWT_SECRET: 'review-check-' + Math.random().toString(36).slice(2),
            AI_FAKE_PROVIDER: '1',
            AI_GENERATION_ENABLED: '1'
        }
    });
function stopServer() {
    if (server.exitCode !== null) return;
    if (process.platform === 'win32') spawnSync('taskkill', ['/PID', String(server.pid), '/T', '/F']);
    else server.kill('SIGTERM');
}
process.on('exit', stopServer);

async function waitForServer() {
    for (let i = 0; i < 120; i++) {
        if (server.exitCode !== null) throw new Error('the test server stopped; see ' + path.join(OUT, 'server.log'));
        try {
            if ((await fetch(BASE + '/review.js')).ok) return;
        } catch (e) { /* not up yet */ }
        await new Promise(r => setTimeout(r, 500));
    }
    throw new Error('the test server did not start');
}

async function api(method, route, token, body) {
    const res = await fetch(BASE + route, {
        method, headers: { Authorization: 'Bearer ' + token, ...(body ? { 'Content-Type': 'application/json' } : {}) },
        body: body ? JSON.stringify(body) : undefined
    });
    return { status: res.status, data: await res.json().catch(() => null) };
}

function silentWav(seconds) {
    const rate = 8000, samples = Math.round(rate * seconds);
    const buf = Buffer.alloc(44 + samples * 2);
    buf.write('RIFF', 0); buf.writeUInt32LE(36 + samples * 2, 4); buf.write('WAVE', 8); buf.write('fmt ', 12);
    buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22); buf.writeUInt32LE(rate, 24);
    buf.writeUInt32LE(rate * 2, 28); buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34); buf.write('data', 36);
    buf.writeUInt32LE(samples * 2, 40);
    return buf;
}

function silentPage() {
    const devices = navigator.mediaDevices;
    if (devices && devices.getDisplayMedia) {
        const capture = devices.getDisplayMedia.bind(devices);
        devices.getDisplayMedia = (constraints = {}) => capture({
            ...constraints,
            audio: constraints.audio ? { ...(typeof constraints.audio === 'object' ? constraints.audio : {}), suppressLocalAudioPlayback: true } : false
        });
    }
    if (window.speechSynthesis) {
        window.speechSynthesis.speak = utterance => setTimeout(() => {
            if (utterance.onstart) utterance.onstart(new Event('start'));
            setTimeout(() => utterance.onend && utterance.onend(new Event('end')), 300);
        }, 0);
        window.speechSynthesis.cancel = () => {};
    }
}

// Average colour of the centre of a frame, as [r, g, b]
function centreColour(file, seconds) {
    const r = spawnSync('ffmpeg', ['-v', 'error', '-ss', String(seconds), '-i', file, '-frames:v', '1',
        '-vf', 'crop=iw/5:ih/5:iw*2/5:ih*2/5,scale=1:1', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'], { maxBuffer: 1 << 20 });
    return [...r.stdout.subarray(0, 3)];
}
const near = (c, target, tol = 60) => c.length === 3 && c.every((v, i) => Math.abs(v - target[i]) <= tol);

const tag = Date.now().toString(36);
const ORANGE = [240, 128, 32];
const chosenClip = path.join(OUT, `harbour-${tag}.mp4`);
run('ffmpeg', ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=0xF08020:size=1280x720:rate=25:duration=10',
    '-vf', "drawbox=x='mod(t*200,1100)':y=300:w=120:h=120:c=white:t=fill", '-pix_fmt', 'yuv420p', '-c:v', 'libx264', chosenClip]);

const bridgePrompt = `a slow aerial shot of a cable-stayed bridge over a river ${tag}`;
const scenes = [
    { type: 'ai_video', concept_id: 'c1', title: 'THE BRIDGE', aadhi_position: 'hidden', prompt: bridgePrompt, narration: 'The bridge carries the road.' },
    { type: 'content', concept_id: 'c1', title: 'FORCES', aadhi_position: 'popup_bottom_left', html: '<p>Loads spread out.</p>',
      side_panel: { type: 'chart', chart_type: 'bar', title: 'Load', data: { labels: ['A', 'B'], datasets: [{ label: 'kN', data: [4, 9] }] } }, narration: 'The chart shows the loads.' },
    { type: 'ai_video', concept_id: 'c1', title: 'THE HARBOUR', aadhi_position: 'hidden', prompt: `container ships in a busy harbour ${tag}`, narration: 'Ships unload their cargo.' },
    { type: 'content', concept_id: 'c1', title: 'THE LIGHTHOUSE', aadhi_position: 'popup_bottom_left', html: '<p>A light for ships.</p>',
      side_panel: { type: 'image', prompt: `a lighthouse in a storm ${tag}` }, narration: 'The lighthouse guides the ships.' }
];

const problems = [];
let browser;
try {
    await waitForServer();
    const token = (await (await fetch(BASE + '/api/login', { method: 'POST', body: new URLSearchParams({ username: 'admin', password: PASSWORD }) })).json()).access_token;
    const stats = async () => (await api('GET', '/api/ai-cache/stats', token)).data;
    const start = await stats();
    check('the test server uses the stand-in AI providers', start.video_provider === 'fake' && start.image_provider === 'fake');

    // The clip the user will choose: described (its file name says nothing)
    const form = new FormData();
    form.append('file', new Blob([fs.readFileSync(chosenClip)]), `VID_${tag}.mp4`);
    const clipId = (await (await fetch(BASE + '/api/assets', { method: 'POST', headers: { Authorization: 'Bearer ' + token }, body: form })).json()).asset.id;
    await api('PATCH', `/api/assets/${clipId}`, token, { description: `orange harbour cranes at work ${tag}` });
    const projectId = (await api('POST', '/save-history', token, { subject_name: 'Review check', session_title: 'Bridges and harbours',
        concept_map: [{ id: 'c1', label: 'Structures' }], scenes })).data.id;

    const { chromium } = await loadPlaywright();
    browser = await chromium.launch({
        channel: 'chrome', headless: true,
        args: ['--auto-accept-this-tab-capture', '--autoplay-policy=no-user-gesture-required', '--disable-audio-output'],
        ignoreDefaultArgs: ['--mute-audio'] // a muted tab records silence; nothing reaches the speakers anyway
    });
    const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, acceptDownloads: true });
    await context.addInitScript(t => localStorage.setItem('jwt_token', t), token);
    await context.addInitScript(silentPage);
    await context.route('**/generate-audio', r => r.fulfill({ json: { status: 'success', audio_url: `/__silence.wav?n=${Math.random()}` } }));
    await context.route('**/__silence.wav*', r => r.fulfill({ status: 200, contentType: 'audio/wav', body: silentWav(5) }));
    const generatorRequests = { video: [], image: [] };
    const page = await context.newPage();
    page.on('pageerror', e => problems.push(`page error: ${e.message}`));
    page.on('console', m => {
        if (m.type() === 'error' && !(m.location().url || '').endsWith('/favicon.ico') && !m.text().startsWith('Logo video play error AbortError')) problems.push(`console: ${m.text()}`);
    });
    page.on('response', r => { if (r.status() >= 400 && !r.url().endsWith('/favicon.ico')) problems.push(`HTTP ${r.status()}: ${r.url()}`); });
    page.on('request', r => {
        if (r.url().endsWith('/generate-ai-video')) generatorRequests.video.push(r.postDataJSON());
        if (r.url().endsWith('/generate-ai-image')) generatorRequests.image.push(r.postDataJSON());
    });

    async function openReview() {
        await page.goto(`${BASE}/?project_id=${projectId}`);
        await page.waitForSelector('#start-overlay', { state: 'visible', timeout: 30000 });
        await page.click('#start-review-btn');
        await page.waitForSelector('.review-overlay.open .review-item', { timeout: 30000 });
    }
    const chip = scene => page.textContent(`.review-item[data-scene="${scene}"] .review-chip`);
    const selectScene = async scene => {
        await page.click(`.review-item[data-scene="${scene}"]`);
        await page.waitForFunction(s => document.querySelector(`.review-item[data-scene="${s}"]`).classList.contains('selected'), scene);
    };
    const act = async (action, wait = /./) => {
        await page.click(`.review-detail [data-action="${action}"]`);
        await page.waitForFunction(re => {
            const st = document.querySelector('.review-status');
            return st && !/Saving|Generating/.test(st.textContent) && new RegExp(re).test(st.textContent);
        }, wait.source, { timeout: 30000 });
    };
    const statusLine = () => page.textContent('.review-status');

    // ---- 1. initial review ----------------------------------------------------------------------------
    await openReview();
    const initial = await page.evaluate(() => ({
        items: [...document.querySelectorAll('.review-item')].map(b => [b.dataset.scene, b.dataset.slot, b.querySelector('.review-chip').textContent]),
        summary: document.querySelector('.review-summary').textContent,
        preview: document.querySelector('.review-detail .review-preview') && document.querySelector('.review-detail .review-preview').dataset.kind
    }));
    check('scenario 1: Visual Review lists every scene visual, all "Needs review"',
        initial.items.length === 4 && initial.items.every(i => /Needs review/.test(i[2])) && /4 scenes · 4 items · ● 4 to check/.test(initial.summary),
        initial.summary);
    check('scenario 1: opening the review generated nothing', generatorRequests.video.length === 0 && generatorRequests.image.length === 0
        && (await stats()).provider_calls.video === start.provider_calls.video, `first preview: ${initial.preview}`);
    await page.screenshot({ path: path.join(OUT, '1-review-opened.png') });

    // ---- 2. Keep ----------------------------------------------------------------------------------------
    await selectScene(1);
    await act('keep', /Kept/);
    const keptNow = await chip(1);
    await openReview();
    check('scenario 2: Keep marks the chart approved, and it stays approved after a reload', /Approved/.test(keptNow) && /Approved/.test(await chip(1)), keptNow);

    // ---- 3. Change to an Asset Library visual ---------------------------------------------------------------
    await selectScene(2);
    await page.click('.review-detail [data-action="change"]');
    await page.click('.review-detail .review-change [data-action="pick"]');
    await page.waitForSelector('.asset-overlay.picking.open', { timeout: 15000 });
    await page.fill('.asset-search', `harbour cranes at work ${tag}`); // matches the description, not the file name
    await page.waitForFunction(id => { const items = document.querySelectorAll('.asset-item'); return items.length === 1 && items[0].dataset.id === id; }, clipId, { timeout: 15000 });
    await page.click(`.asset-item[data-id="${clipId}"]`);
    await page.waitForSelector('.asset-pick', { timeout: 15000 });
    await page.screenshot({ path: path.join(OUT, '3a-asset-picker.png') });
    await page.click('.asset-pick');
    await page.waitForFunction(() => /Changed/.test((document.querySelector('.review-status') || {}).textContent || ''), null, { timeout: 30000 });
    const changedNow = { chip: await chip(2), src: await page.getAttribute('.review-detail .review-preview video', 'src') };
    await page.screenshot({ path: path.join(OUT, '3b-changed.png') });
    await openReview();
    await selectScene(2);
    const changedAfter = { chip: await chip(2), src: await page.getAttribute('.review-detail .review-preview video', 'src') };
    check('scenario 3: the chosen library clip is the visual (changed), also after a reload',
        /Changed/.test(changedNow.chip) && changedNow.src.includes(`/api/assets/${clipId}/`) && /Changed/.test(changedAfter.chip) && changedAfter.src.includes(`/api/assets/${clipId}/`),
        changedAfter.chip);

    // ---- 4. Remove --------------------------------------------------------------------------------------------
    await selectScene(3);
    await act('remove', /Removed/);
    const removedNow = { chip: await chip(3), preview: await page.textContent('.review-detail .review-preview') };
    await openReview();
    check('scenario 4: Remove leaves the scene without a visual, also after a reload',
        // (Phase 21: the chip says the state in words — "Removed" — the preview still says the scene has no visual)
        /Removed/.test(removedNow.chip) && /No visual for this scene/.test(removedNow.preview) && /Removed/.test(await chip(3)), removedNow.chip);

    // ---- 5. AI cache ---------------------------------------------------------------------------------------------
    await selectScene(0);
    const beforeAi = await stats();
    await page.click('.review-detail [data-action="change"]');
    await page.click('.review-detail .review-change [data-action="generate"]'); // "Generate AI video" (the planned visual)
    await page.waitForFunction(() => /Generated new video|Reused existing video|No new visual|could not/.test((document.querySelector('.review-status') || {}).textContent || ''), null, { timeout: 30000 });
    const firstStatus = await statusLine();
    const firstAsset = await page.evaluate(() => slides[0].visual_plan.main.asset_id);
    const afterFirst = await stats();
    const again = await page.evaluate(p => aiMediaApi.generateVideo(p), bridgePrompt); // the same request, as an export in "all" mode makes it
    const afterAgain = await stats();
    check('scenario 5: the first request is a cache miss that generates one video',
        /Generated new video/.test(firstStatus) && afterFirst.provider_calls.video - beforeAi.provider_calls.video === 1 && !!firstAsset, firstStatus);
    check('scenario 5: the same request again is a cache hit: same asset, no provider call',
        again.cache_hit === true && again.asset_id === firstAsset && afterAgain.provider_calls.video === afterFirst.provider_calls.video);

    // ---- 6. New AI version -----------------------------------------------------------------------------------------
    await page.click('.review-detail [data-action="change"]');
    const regenerateLabel = await page.textContent('.review-detail .review-change [data-action="generate"]');
    await page.click('.review-detail .review-change [data-action="generate"]');
    await page.waitForFunction(() => /Generated new video|No new visual|could not/.test((document.querySelector('.review-status') || {}).textContent || ''), null, { timeout: 30000 });
    const newAsset = await page.evaluate(() => slides[0].visual_plan.main.asset_id);
    const afterForce = await stats();
    const forcedRequests = generatorRequests.video.filter(b => b.force_regenerate === true);
    const oldAsset = (await api('GET', `/api/assets/${firstAsset}`, token)).data;
    check('scenario 6: "Generate new AI version" makes a new asset with exactly one provider call',
        /new AI version/.test(regenerateLabel) && newAsset && newAsset !== firstAsset && forcedRequests.length === 1
        && afterForce.provider_calls.video - afterAgain.provider_calls.video === 1 && /Changed/.test(await chip(0)), `${firstAsset.slice(0, 8)} -> ${String(newAsset).slice(0, 8)}`);
    check('scenario 6: the earlier AI version still exists and plays', oldAsset.status === 'ready'
        && (await fetch(`${BASE}/api/assets/${firstAsset}/content`, { headers: { Authorization: 'Bearer ' + token } })).ok);
    await page.screenshot({ path: path.join(OUT, '6-new-version.png') });

    // ---- 7. Export follows the review -------------------------------------------------------------------------------------
    await page.click('.review-panel .export-close');
    const reviewedPlans = await page.evaluate(() => slides.map(s => s.visual_plan || {}));
    await page.evaluate(() => {
        window.visualSamples = {};
        setInterval(() => {
            if (!exportFlow.recording || !window.exportStartTime || isIntroRunning) return;
            const video = document.getElementById('active-ai-video');
            const img = document.getElementById('side-image-display');
            window.visualSamples[currentSlide] = {
                video: video && video.readyState >= 2 && video.offsetParent !== null ? video.getAttribute('src') : null,
                image: document.getElementById('side-image-panel').classList.contains('active') && img.naturalWidth > 0 ? img.getAttribute('src') : null,
                chart: document.getElementById('side-chart-panel').classList.contains('active'),
                conceptMap: document.getElementById('concept-map-panel').classList.contains('active')
            };
        }, 100);
    });
    const beforeExport = await stats();
    await page.click('#start-videos-btn');
    await page.click('.export-start-btn');
    const warnings = [];
    for (;;) {
        const startBtn = page.locator('.export-actions button', { hasText: 'Start Recording' });
        const anyway = page.locator('.export-actions button', { hasText: 'Record anyway' });
        await Promise.race([startBtn.waitFor({ timeout: 300000 }), anyway.waitFor({ timeout: 300000 })]);
        if (await anyway.isVisible()) {
            warnings.push(await page.textContent('.export-message'));
            await anyway.click();
            continue;
        }
        await startBtn.click();
        break;
    }
    let outcome = null;
    const began = Date.now();
    while (!outcome && Date.now() - began < 420000) {
        await page.waitForTimeout(500);
        outcome = await page.evaluate(() => (!document.querySelector('.export-ready').hidden ? 'ready'
            : document.querySelector('.export-message').getAttribute('data-kind') === 'error' ? 'error: ' + document.querySelector('.export-message').textContent : null));
    }
    const samples = await page.evaluate(() => window.visualSamples);
    const afterExport = await stats();
    const strip = url => (url || '').split('?')[0];
    check('scenario 7: the export finished without warnings', outcome === 'ready' && warnings.length === 0, `${outcome}; ${warnings.join(' | ')}`);
    check('scenario 7: the recording showed the reviewed visuals',
        samples[0] && strip(samples[0].video).includes(newAsset) || (samples[0] && strip(samples[0].video) === strip(reviewedPlans[0].main.url)),
        JSON.stringify(Object.fromEntries(Object.entries(samples).map(([k, v]) => [k, strip(v.video || v.image) || (v.chart ? 'chart' : v.conceptMap ? 'concept map' : '?')]))));
    check('scenario 7: the chosen clip played in its scene, the chart in its scene, and the removed scene had no visual',
        samples[2] && strip(samples[2].video).includes(`/api/assets/${clipId}/`) && samples[1] && samples[1].chart
        && samples[3] && !samples[3].image && samples[3].conceptMap);
    check('scenario 7: nothing was generated for the export (the removed AI image was never requested)',
        afterExport.provider_calls.video === beforeExport.provider_calls.video && afterExport.provider_calls.image === start.provider_calls.image
        && generatorRequests.image.length === 0);

    const [download] = await Promise.all([page.waitForEvent('download'), page.click('.export-ready button:has-text("Download Video")')]);
    const file = path.join(OUT, download.suggestedFilename());
    await download.saveAs(file);
    const log = await page.evaluate(() => window.exportSceneLog || []);
    const duration = parseFloat(JSON.parse(run('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'json', file]).stdout).format.duration);
    console.log(`NOTE  scene start times in the recording: ${log.map((s, i) => `${i + 1}@${s.t.toFixed(1)}s`).join(' ')}`);
    const harbourEnd = (log[3] ? log[3].t : duration) - 0.8;
    const colour = log.length === 4 ? centreColour(file, harbourEnd) : [];
    check('scenario 7: the downloaded video shows the chosen (orange) clip in its scene', near(colour, ORANGE), `centre rgb(${colour})`);

    // ---- On a phone: the review stacks, stays inside the screen, and labels its image previews ---------------
    const phone = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await phone.addInitScript(t => localStorage.setItem('jwt_token', t), token);
    await phone.addInitScript(silentPage);
    const phonePage = await phone.newPage();
    await phonePage.goto(`${BASE}/?project_id=${projectId}`);
    await phonePage.waitForFunction(() => typeof openVisualReview === 'function' && slides.length > 0, null, { timeout: 30000 });
    await phonePage.evaluate(() => openVisualReview());
    await phonePage.waitForSelector('.review-overlay.open .review-item', { timeout: 30000 });
    const layout = await phonePage.evaluate(() => {
        const panel = document.querySelector('.review-panel').getBoundingClientRect();
        const list = document.querySelector('.review-list').getBoundingClientRect();
        const detail = document.querySelector('.review-detail').getBoundingClientRect();
        const buttons = [...document.querySelectorAll('.review-detail button')].filter(b => b.offsetParent !== null);
        return { fits: panel.left >= 0 && panel.right <= innerWidth + 1, stacked: detail.top >= list.bottom - 1,
            noSideScroll: document.documentElement.scrollWidth <= innerWidth,
            buttonsInside: buttons.every(b => b.getBoundingClientRect().right <= innerWidth + 1),
            labelled: buttons.every(b => (b.textContent || b.getAttribute('aria-label') || '').trim().length > 0) };
    });
    check('on a phone the review stacks, fits the screen and every button is labelled', Object.values(layout).every(Boolean), JSON.stringify(layout));
    await phonePage.screenshot({ path: path.join(OUT, '8-phone.png') });
    await phone.close();

    check('no console errors, page errors or failed requests', problems.length === 0, problems.join(' | '));
    await context.close();
} catch (err) {
    check('the check ran to the end', false, err.stack || String(err));
} finally {
    if (browser) await browser.close();
    stopServer();
}

const failed = results.filter(r => !r.ok).length;
console.log(`\n${results.length - failed}/${results.length} checks passed. Screenshots, video and server log: ${OUT}`);
process.exit(failed ? 1 : 0);
