"""Alembic: upgrade head on an empty SQLite, no drift (``alembic check``), downgrade base."""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

from aadhi.config import ROOT_DIR
from aadhi.db import Base
from alembic import command


def _config(db_path: Path) -> Config:
    cfg = Config(str(ROOT_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT_DIR / "alembic"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path.as_posix()}")
    cfg.attributes["configure_logger"] = False
    return cfg


def test_linear_revision_history():
    script = ScriptDirectory.from_config(_config(Path("unused.db")))
    revisions = list(script.walk_revisions())  # newest first
    assert [r.revision for r in revisions] == [
        "0006_visual_reviews", "0005_library_items", "0004_claim_operation", "0003_asset_claims", "0002", "0001"
    ]
    assert [r.down_revision for r in revisions] == [
        "0005_library_items", "0004_claim_operation", "0003_asset_claims", "0002", "0001", None
    ]
    assert script.get_heads() == ["0006_visual_reviews"]


def test_upgrade_check_downgrade(app_env, tmp_path):
    db = tmp_path / "migrated.db"
    cfg = _config(db)
    command.upgrade(cfg, "head")

    engine = create_engine(f"sqlite:///{db.as_posix()}")
    try:
        insp = inspect(engine)
        tables = set(insp.get_table_names())
        assert set(Base.metadata.tables) <= tables and "alembic_version" in tables
        partial = [ix for ix in insp.get_indexes("jobs") if ix["name"] == "uq_jobs_active_version"]
        assert partial and partial[0]["unique"]
        fks = {fk["name"]: fk for fk in insp.get_foreign_keys("projects")}
        cyclic = fks["fk_projects_current_version_id_project_versions"]
        assert cyclic["referred_table"] == "project_versions" and cyclic["options"].get("ondelete") == "SET NULL"
        assert insp.get_pk_constraint("users")["name"] == "pk_users"
    finally:
        engine.dispose()

    con = sqlite3.connect(db)
    try:
        sql = con.execute("SELECT sql FROM sqlite_master WHERE name='uq_jobs_active_version'").fetchone()[0]
        assert "WHERE status IN ('queued','running','awaiting_review')" in sql
        assert con.execute("PRAGMA foreign_key_check").fetchall() == []
    finally:
        con.close()

    command.check(cfg)  # raises AutogenerateDiffsDetected on any model/schema drift

    command.downgrade(cfg, "base")
    engine = create_engine(f"sqlite:///{db.as_posix()}")
    try:
        assert set(inspect(engine).get_table_names()) <= {"alembic_version"}
    finally:
        engine.dispose()
    command.upgrade(cfg, "head")  # and back up again


def test_check_detects_drift(app_env, tmp_path):
    db = tmp_path / "drift.db"
    cfg = _config(db)
    command.upgrade(cfg, "head")
    con = sqlite3.connect(db)
    con.execute("DROP INDEX ix_jobs_claim")
    con.commit()
    con.close()
    with pytest.raises(AutogenerateDiffsDetected):
        command.check(cfg)


def test_offline_postgres_sql(app_env, capsys):
    cfg = _config(Path("unused.db"))
    cfg.set_main_option("sqlalchemy.url", "postgresql+psycopg://user:pw@localhost/aadhi")
    command.upgrade(cfg, "head", sql=True)
    sql = capsys.readouterr().out
    assert "settings JSONB NOT NULL" in sql
    assert "ALTER TABLE projects ADD CONSTRAINT fk_projects_current_version_id_project_versions" in sql
    assert "CREATE UNIQUE INDEX uq_jobs_active_version ON jobs (version_id) WHERE status IN" in sql


# --- 0002: saved API keys + usage_events.billed_to ---------------------------------------------------


def test_0002_upgrades_existing_data(app_env, tmp_path):
    db = tmp_path / "upgrade.db"
    cfg = _config(db)
    command.upgrade(cfg, "0001")
    con = sqlite3.connect(db)
    con.execute(
        "INSERT INTO usage_events (provider, model, operation, input_tokens, output_tokens, characters, seconds, "
        "units, cost_usd, meta, created_at) VALUES ('gemini', 'm', 'llm', 1, 1, 0, 0, 0, 0.5, '{}', "
        "'2026-10-01 00:00:00')"
    )
    con.commit()
    con.close()

    command.upgrade(cfg, "head")
    engine = create_engine(f"sqlite:///{db.as_posix()}")
    try:
        insp = inspect(engine)
        columns = {c["name"]: c for c in insp.get_columns("api_credentials")}
        assert set(columns) >= {"owner_key", "user_id", "provider", "ciphertext", "key_hint", "created_by_id",
                                "last_verified_at", "last_error", "created_at", "updated_at"}
        uniques = {u["name"]: u["column_names"] for u in insp.get_unique_constraints("api_credentials")}
        assert uniques["uq_api_credentials_owner_provider"] == ["owner_key", "provider"]
        fks = {fk["constrained_columns"][0]: fk for fk in insp.get_foreign_keys("api_credentials")}
        assert fks["user_id"]["options"].get("ondelete") == "CASCADE"
        assert fks["created_by_id"]["options"].get("ondelete") == "SET NULL"
        assert "billed_to" in {c["name"] for c in insp.get_columns("usage_events")}
    finally:
        engine.dispose()
    con = sqlite3.connect(db)
    try:
        assert con.execute("SELECT billed_to FROM usage_events").fetchall() == [("server",)]  # existing rows
        head = ScriptDirectory.from_config(cfg).get_current_head()  # later migrations may follow 0002
        assert con.execute("SELECT version_num FROM alembic_version").fetchall() == [(head,)]
    finally:
        con.close()
    command.check(cfg)
    command.downgrade(cfg, "0001")
    con = sqlite3.connect(db)
    try:
        assert "billed_to" not in {row[1] for row in con.execute("PRAGMA table_info(usage_events)")}
        assert con.execute("SELECT count(*) FROM usage_events").fetchone() == (1,)
        assert con.execute("SELECT name FROM sqlite_master WHERE name='api_credentials'").fetchone() is None
    finally:
        con.close()


def test_0002_is_idempotent_after_create_all(app_env, tmp_path):
    """A development database at 0001 whose startup ``create_all`` already made the new table/column."""
    from aadhi.dev_schema import add_missing_columns

    db = tmp_path / "dev.db"
    cfg = _config(db)
    command.upgrade(cfg, "0001")
    engine = create_engine(f"sqlite:///{db.as_posix()}")
    try:
        Base.metadata.create_all(engine)  # what the API does at startup in development
        assert add_missing_columns(engine) == ["usage_events.billed_to"]
        assert add_missing_columns(engine) == []
    finally:
        engine.dispose()
    command.upgrade(cfg, "head")
    command.check(cfg)


def test_offline_postgres_sql_includes_0002(app_env, capsys):
    cfg = _config(Path("unused.db"))
    cfg.set_main_option("sqlalchemy.url", "postgresql+psycopg://user:pw@localhost/aadhi")
    command.upgrade(cfg, "0001:head", sql=True)
    sql = capsys.readouterr().out
    assert "CREATE TABLE api_credentials" in sql
    assert "ALTER TABLE usage_events ADD COLUMN billed_to VARCHAR(8) DEFAULT 'server' NOT NULL" in sql
