"""Initial schema (Aadhi EduEngine v2).

Autogenerated from ``aadhi.models`` and hand-checked:

* JSON documents use ``JSON`` with a ``JSONB`` variant on PostgreSQL (``aadhi.models.JsonDoc``);
* constraint/index names follow ``aadhi.db.NAMING_CONVENTION``;
* ``uq_jobs_active_version`` is a partial unique index on both SQLite and PostgreSQL;
* ``projects.current_version_id`` -> ``project_versions.id`` is the ``use_alter`` FK of the
  projects <-> project_versions cycle: created after both tables and dropped first on downgrade.

Revision ID: 0001
Revises:
Create Date: 2026-10-01
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSON_DOC = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")
ACTIVE_JOB_WHERE = (
    "status IN ('queued','running','awaiting_review') AND kind IN "
    "('generate_lecture','regenerate_scene','build_assets','translate')"
)
CURRENT_VERSION_FK = "fk_projects_current_version_id_project_versions"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("daily_budget_usd", sa.Float(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("meta", JSON_DOC, nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_assets_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("key", name=op.f("uq_assets_key")),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_kind"), ["kind"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("subject_name", sa.String(length=255), nullable=False),
        sa.Column("unit_name", sa.String(length=255), nullable=False),
        sa.Column("session_number", sa.String(length=64), nullable=False),
        sa.Column("session_title", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("settings", JSON_DOC, nullable=False),
        sa.Column("next_version_number", sa.Integer(), nullable=False),
        sa.Column("current_version_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("ix_projects_owner_updated", ["owner_id", "updated_at"], unique=False)

    op.create_table(
        "asset_refs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("asset_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_asset_refs_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_refs")),
        sa.UniqueConstraint("project_id", "asset_key", name="uq_asset_refs_project_asset"),
    )
    with op.batch_alter_table("asset_refs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_refs_asset_key"), ["asset_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_refs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "project_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=True),
        sa.Column("screenplay", JSON_DOC, nullable=True),
        sa.Column("timeline", JSON_DOC, nullable=True),
        sa.Column("asset_manifest", JSON_DOC, nullable=True),
        sa.Column("issues", JSON_DOC, nullable=False),
        sa.Column("generation_meta", JSON_DOC, nullable=False),
        sa.Column("issue_counts", JSON_DOC, nullable=False),
        sa.Column("has_timeline", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("built_revision", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_project_versions_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_versions_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["project_versions.id"],
            name=op.f("fk_project_versions_source_version_id_project_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_versions")),
        sa.UniqueConstraint("project_id", "number", name="uq_project_versions_project_number"),
    )
    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_versions_project_id"), ["project_id"], unique=False)

    # The cyclic FK of projects <-> project_versions: added once both tables exist.
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_foreign_key(
            op.f(CURRENT_VERSION_FK), "project_versions", ["current_version_id"], ["id"], ondelete="SET NULL"
        )

    op.create_table(
        "source_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extracted_key", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_source_documents_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_documents_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_documents_sha256"), ["sha256"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", JSON_DOC, nullable=False),
        sa.Column("result", JSON_DOC, nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("locked_by", sa.String(length=160), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_jobs_project_id_projects"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_jobs_version_id_project_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_claim", ["status", "kind", "priority", "run_after"], unique=False)
        batch_op.create_index("ix_jobs_project_created", ["project_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "uq_jobs_active_version",
            ["version_id"],
            unique=True,
            sqlite_where=sa.text(ACTIVE_JOB_WHERE),
            postgresql_where=sa.text(ACTIVE_JOB_WHERE),
        )

    op.create_table(
        "share_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_share_links_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_share_links_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_share_links_version_id_project_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_links")),
        sa.UniqueConstraint("token", name=op.f("uq_share_links_token")),
    )
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_share_links_project_id"), ["project_id"], unique=False)

    op.create_table(
        "analytics_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("share_link_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("viewer_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=True),
        sa.Column("data", JSON_DOC, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_analytics_events_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["share_link_id"],
            ["share_links.id"],
            name=op.f("fk_analytics_events_share_link_id_share_links"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_analytics_events_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_analytics_events_version_id_project_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.create_index("ix_analytics_project_event", ["project_id", "event"], unique=False)
        batch_op.create_index("ix_analytics_project_time", ["project_id", "created_at"], unique=False)
        batch_op.create_index("ix_analytics_share_time", ["share_link_id", "created_at"], unique=False)

    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("data", JSON_DOC, nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
    )
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.create_index("ix_job_events_job_id_id", ["job_id", "id"], unique=False)

    op.create_table(
        "renders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("built_revision", sa.Integer(), nullable=True),
        sa.Column("video_asset_key", sa.String(length=128), nullable=True),
        sa.Column("srt_asset_key", sa.String(length=128), nullable=True),
        sa.Column("vtt_asset_key", sa.String(length=128), nullable=True),
        sa.Column("chapters_text", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("options", JSON_DOC, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_renders_job_id_jobs"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_renders_version_id_project_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_renders")),
    )
    with op.batch_alter_table("renders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_renders_version_id"), ["version_id"], unique=False)

    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("characters", sa.Integer(), nullable=False),
        sa.Column("seconds", sa.Float(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("meta", JSON_DOC, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_usage_events_job_id_jobs"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_usage_events_project_id_projects"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usage_events_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_events_job_id"), ["job_id"], unique=False)
        batch_op.create_index("ix_usage_project_time", ["project_id", "created_at"], unique=False)
        batch_op.create_index("ix_usage_user_time", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(op.f(CURRENT_VERSION_FK), type_="foreignkey")

    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_user_time")
        batch_op.drop_index("ix_usage_project_time")
        batch_op.drop_index(batch_op.f("ix_usage_events_job_id"))

    op.drop_table("usage_events")
    with op.batch_alter_table("renders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_renders_version_id"))

    op.drop_table("renders")
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.drop_index("ix_job_events_job_id_id")

    op.drop_table("job_events")
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.drop_index("ix_analytics_share_time")
        batch_op.drop_index("ix_analytics_project_time")
        batch_op.drop_index("ix_analytics_project_event")

    op.drop_table("analytics_events")
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_share_links_project_id"))

    op.drop_table("share_links")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_jobs_active_version", sqlite_where=sa.text(ACTIVE_JOB_WHERE), postgresql_where=sa.text(ACTIVE_JOB_WHERE)
        )
        batch_op.drop_index(batch_op.f("ix_jobs_user_id"))
        batch_op.drop_index("ix_jobs_project_created")
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_source_documents_project_id"))

    op.drop_table("source_documents")
    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_versions_project_id"))

    op.drop_table("project_versions")
    with op.batch_alter_table("asset_refs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_refs_project_id"))
        batch_op.drop_index(batch_op.f("ix_asset_refs_asset_key"))

    op.drop_table("asset_refs")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_owner_updated")

    op.drop_table("projects")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_kind"))

    op.drop_table("assets")
    op.drop_table("users")
    # ### end Alembic commands ###
