// @ts-check
/**
 * Lazy loader for self-hosted third-party libraries (web/vendor, generated by
 * `npm run vendor`). Nothing is fetched from a CDN, so the CSP is `script-src 'self'` and the
 * render worker works offline. Load a library only when a scene needs it.
 */

const VENDOR = '/web/vendor';

/** UMD scripts and the global they define. */
/** @type {Record<string, { path: string, global: string }>} */
export const LIBS = {
  chartjs: { path: 'chartjs/chart.umd.min.js', global: 'Chart' },
  mathjs: { path: 'mathjs/math.js', global: 'math' },
  prism: { path: 'prism/prism.js', global: 'Prism' },
  dompurify: { path: 'dompurify/purify.min.js', global: 'DOMPurify' },
  marked: { path: 'marked/marked.umd.js', global: 'marked' },
};

/** @type {Map<string, Promise<any>>} */
const pending = new Map();

/**
 * @param {string} src
 * @returns {Promise<void>}
 */
function injectScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.async = true;
    s.onload = () => resolve();
    s.onerror = () => reject(new Error(`failed to load ${src}`));
    document.head.appendChild(s);
  });
}

/**
 * Load a UMD library by name and resolve to its global.
 * @param {string} name
 * @returns {Promise<any>}
 */
export function loadLib(name) {
  const spec = LIBS[name];
  if (!spec) return Promise.reject(new Error(`unknown lib ${name}`));
  const existing = /** @type {any} */ (window)[spec.global];
  if (existing) return Promise.resolve(existing);
  let p = pending.get(name);
  if (!p) {
    p = injectScript(`${VENDOR}/${spec.path}`).then(() => /** @type {any} */ (window)[spec.global]);
    p.catch(() => pending.delete(name));
    pending.set(name, p);
  }
  return p;
}

/** three.js is an ES module (r160+). @returns {Promise<any>} */
export function loadThree() {
  return import(/* @vite-ignore */ `${VENDOR}/three/three.module.js`);
}

/**
 * Prism + a language component (code board items). Unknown languages fall back to plain text.
 * @param {string | null | undefined} language
 */
export async function loadPrism(language) {
  const Prism = await loadLib('prism');
  const lang = (language || '').toLowerCase();
  const known = ['python', 'c', 'cpp', 'java', 'javascript', 'bash', 'sql', 'matlab', 'verilog'];
  if (known.includes(lang) && !Prism.languages[lang]) {
    if (['c', 'cpp', 'java', 'javascript'].includes(lang) && !Prism.languages.clike) {
      await injectScript(`${VENDOR}/prism/components/prism-clike.min.js`);
    }
    if (lang === 'cpp' && !Prism.languages.c) await injectScript(`${VENDOR}/prism/components/prism-c.min.js`);
    await injectScript(`${VENDOR}/prism/components/prism-${lang}.min.js`);
  }
  return Prism;
}

/** @type {Promise<any> | null} */
let mathJaxPromise = null;

/**
 * Load MathJax 3 (SVG output) locked down for untrusted TeX:
 *  - no page scanning (inline/display delimiters empty): only renderTex() converts TeX;
 *  - `require` removed and the html/bbox/unicode autoloads disabled (no \href \class \style
 *    \cssId \bbox \unicode); ui/safe filters any remaining URLs/classes/ids/styles.
 * @returns {Promise<any>} window.MathJax once ready
 */
export function loadMathJax() {
  if (mathJaxPromise) return mathJaxPromise;
  mathJaxPromise = new Promise((resolve, reject) => {
    /** @type {any} */ (window).MathJax = {
      loader: { load: ['ui/safe'], paths: { mathjax: `${VENDOR}/mathjax` } },
      tex: {
        inlineMath: [],
        displayMath: [],
        processEscapes: false,
        packages: { '[-]': ['require'] },
        autoload: { html: [], bbox: [], unicode: [] },
        maxBuffer: 5 * 1024,
        maxMacros: 1000,
      },
      options: {
        enableMenu: false,
        enableExplorer: false,
        enableAssistiveMml: false,
        menuOptions: { settings: { assistiveMml: false, explorer: false } },
        safeOptions: { allow: { URLs: 'none', classes: 'none', cssIDs: 'none', styles: 'none' } },
      },
      svg: { fontCache: 'local' },
      startup: {
        typeset: false,
        ready() {
          const mj = /** @type {any} */ (window).MathJax;
          mj.startup.defaultReady();
          mj.startup.promise.then(() => {
            // renderTex never typesets the page, so MathJax never installs its SVG stylesheet;
            // without it hidden helper nodes render visibly and formulas appear twice.
            try {
              const sheet = mj.svgStylesheet();
              if (sheet && !document.getElementById('MJX-SVG-styles')) document.head.appendChild(sheet);
            } catch (e) {
              console.warn('MathJax stylesheet', e);
            }
            resolve(mj);
          }, reject);
        },
      },
    };
    injectScript(`${VENDOR}/mathjax/tex-svg.js`).catch((e) => {
      mathJaxPromise = null;
      reject(e);
    });
  });
  return mathJaxPromise;
}

/** Serialise conversions: MathJax is not re-entrant. */
let texChain = Promise.resolve();

/**
 * Convert one TeX string to an SVG element. Never scans the page; never touches HTML.
 * @param {string} latex
 * @param {boolean} display
 * @returns {Promise<Element>}
 */
export function renderTex(latex, display) {
  const job = texChain.then(async () => {
    const mj = await loadMathJax();
    const node = await mj.tex2svgPromise(String(latex), { display });
    return /** @type {Element} */ (node);
  });
  texChain = job.then(
    () => undefined,
    () => undefined,
  );
  return job;
}

/** Resolves when every queued TeX conversion has finished (render mode readiness). */
export function texIdle() {
  return texChain;
}
