"""Generate ``.env.example`` from ``aadhi.config.Settings``.

    python scripts/gen_env_example.py            # rewrite .env.example
    python scripts/gen_env_example.py --check    # exit 1 if .env.example is out of date (CI)
    python scripts/gen_env_example.py --stdout   # print instead of writing

Names, defaults and types come from the pydantic model; descriptions come from the inline comments
and ``# --- Section ---`` headers in ``aadhi/config.py``. The Settings class is introspected, never
instantiated, so no ``.env`` file or environment value is read. Secrets are always emitted empty.
"""

from __future__ import annotations

import argparse
import ast
import io
import re
import sys
import tokenize
import types
import typing
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:  # allow `python scripts/gen_env_example.py` from anywhere
    sys.path.insert(0, str(ROOT))

from pydantic import SecretStr  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402
from pydantic_core import PydanticUndefined  # noqa: E402

from aadhi import config  # noqa: E402

OUTPUT = ROOT / ".env.example"
CONFIG_SOURCE = Path(config.__file__)
_SECTION_RE = re.compile(r"^#\s*-{2,}\s*(?P<title>[^-].*?)\s*-*\s*$")

HEADER = """\
# Aadhi EduEngine v2 configuration.
# GENERATED by scripts/gen_env_example.py from aadhi/config.py - do not edit by hand.
#
# Copy to .env and set what you need; real environment variables override .env.
# Commented lines show the built-in default. Secrets are listed empty: never commit real values.
#
# Offline demo (no API keys, no cost):
#   LLM_PROVIDER=fake  TTS_PROVIDER=fake  IMAGE_PROVIDER=fake  VIDEO_PROVIDER=fake
# Production checklist: APP_ENV=production, JWT_SECRET (>= 32 chars), BASE_URL=https://...,
#   DATABASE_URL=postgresql://..., WORKER_MODE=external, STORAGE_LOCAL_DIR outside the source tree
#   (or STORAGE_BACKEND=s3). See docs/OPERATIONS.md.
"""


# Variables only docker-compose.yml interpolates (the app never reads them). Kept in this generator
# so .env.example stays the single template for .env.
COMPOSE_SECTION = """\
# --- Docker Compose only (docker-compose.yml interpolation; see docs/OPERATIONS.md section 4) -------
# Required by `docker compose`; ADMIN_PASSWORD above is needed only until the first admin exists.
POSTGRES_PASSWORD=
# POSTGRES_USER=aadhi
# POSTGRES_DB=aadhi
# Host port of the API (bound to 127.0.0.1; put a TLS reverse proxy in front)
# AADHI_PORT=8000
# Compose network; the host's reverse proxy appears as the gateway, which is trusted for X-Forwarded-*
# AADHI_SUBNET=172.30.0.0/24
# AADHI_GATEWAY=172.30.0.1
# uvicorn --proxy-headers trust list (default: AADHI_GATEWAY)
# FORWARDED_ALLOW_IPS=172.30.0.1
# Render worker resources
# RENDER_WORKER_CONCURRENCY=1
# RENDER_WORKER_CPUS=4
# RENDER_WORKER_MEMORY=6g
# Image tags
# AADHI_IMAGE=aadhi-eduengine:latest
# AADHI_IMAGE_DOCKER=aadhi-eduengine:docker-cli
# docker-sandbox profile (free-form Manim): host work dir owned by uid 1000, docker group id
# MANIM_HOST_TMP=/var/lib/aadhi/manim-tmp
# DOCKER_GID=999
"""


@dataclass(frozen=True)
class FieldDoc:
    name: str
    section: str | None
    comment: str


def parse_comments(source: str, class_name: str = "Settings") -> dict[str, FieldDoc]:
    """Field name -> (section header, trailing comment) from the Settings class source."""
    tree = ast.parse(source)
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == class_name)
    comments: dict[int, str] = {}
    full_line: dict[int, str] = {}
    for tok in tokenize.generate_tokens(io.StringIO(source).readline):
        if tok.type == tokenize.COMMENT:
            comments[tok.start[0]] = tok.string
            if not tok.line[: tok.start[1]].strip():
                full_line[tok.start[0]] = tok.string
    docs: dict[str, FieldDoc] = {}
    section: str | None = None
    prev_end = cls.lineno
    for node in cls.body:
        start = node.lineno
        for line in range(prev_end + 1, start):
            m = _SECTION_RE.match(full_line.get(line, ""))
            if m:
                section = m.group("title").strip()
        prev_end = node.end_lineno or start
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            end = node.end_lineno or start
            raw = next((comments[ln] for ln in range(end, start - 1, -1) if ln in comments and ln not in full_line), "")
            docs[node.target.id] = FieldDoc(node.target.id, section, raw.lstrip("#").strip())
    return docs


def _flatten(annotation: Any) -> list[Any]:
    origin = typing.get_origin(annotation)
    if origin in (typing.Union, types.UnionType):
        return [a for arg in typing.get_args(annotation) for a in _flatten(arg)]
    if origin is typing.Annotated:
        return _flatten(typing.get_args(annotation)[0])
    return [annotation]


def is_secret(annotation: Any) -> bool:
    """SecretStr or list[SecretStr] (possibly Optional / Annotated)."""
    for part in _flatten(annotation):
        if part is SecretStr:
            return True
        if typing.get_origin(part) in (list, tuple, set) and any(is_secret(a) for a in typing.get_args(part)):
            return True
    return False


def literal_options(annotation: Any) -> list[str]:
    for part in _flatten(annotation):
        if typing.get_origin(part) is typing.Literal:
            return [str(a) for a in typing.get_args(part)]
    return []


def default_of(field: FieldInfo) -> Any:
    if field.default is not PydanticUndefined:
        return field.default
    if field.default_factory is not None:
        return field.default_factory()  # type: ignore[call-arg]
    return None


def render_value(value: Any) -> str:
    """Environment-file representation of a default value."""
    if value is None:
        return ""
    if isinstance(value, SecretStr):
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, Path):
        try:
            return "./" + value.resolve().relative_to(ROOT).as_posix()
        except ValueError:
            return value.as_posix()
    if isinstance(value, list | tuple | set):
        return ",".join(render_value(v) for v in value)
    text = str(value)
    if re.search(r"[\s#'\"=]", text):
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


# Descriptions for settings without an inline comment in aadhi/config.py (comments there win).
EXTRA_DESCRIPTIONS: dict[str, str] = {
    "app_env": "production enables strict startup checks (validate_for_runtime)",
    "data_dir": "runtime data: SQLite DB, storage, dev JWT secret, generated admin password",
    "web_dir": "frontend files served under /web",
    "log_level": "DEBUG | INFO | WARNING | ERROR",
    "max_json_body_mb": "maximum JSON request body",
    "database_url": "postgresql://user:pass@host:5432/db in production; empty = sqlite:///<data_dir>/aadhi.db",
    "jwt_secret": "session signing key; required (>= 32 chars) in production, dev generates one under DATA_DIR",
    "jwt_ttl_hours": "session lifetime",
    "admin_username": "bootstrap admin account name",
    "password_min_length": "minimum password length for new passwords",
    "s3_bucket": "bucket for STORAGE_BACKEND=s3 (S3, Cloudflare R2, MinIO)",
    "s3_access_key_id": "S3/R2 access key (or use the instance role)",
    "s3_secret_access_key": "S3/R2 secret key",
    "s3_prefix": "key prefix inside the bucket",
    "upload_max_mb": "maximum upload size",
    "job_max_attempts": "attempts before a job fails permanently",
    "job_poll_interval_seconds": "idle worker poll interval",
    "llm_provider": "default AI engine; a lecture can pick another configured engine; fake = offline deterministic demo mode",
    "llm_model_plan": "Gemini model for lecture planning (a gpt-*/claude-* name here configures that engine instead)",
    "llm_model_script": "Gemini model for scene writing",
    "llm_model_critic": "Gemini model for the critic / judge",
    "llm_model_fast": "Gemini model for small utility calls",
    "llm_max_parallel": "concurrent LLM calls per process",
    "llm_timeout_seconds": "cap on one attempt of a Gemini / OpenAI LLM call (Claude calls use ANTHROPIC_TIMEOUT_SECONDS)",
    "llm_first_response_timeout_seconds": "longest wait for an OpenAI / Claude call to start answering, plus time to upload a large document; a request with no answer by then is retried (10-600)",
    "llm_idle_timeout_seconds": "longest silence once an OpenAI answer is streaming (Claude: between keep-alive pings), then the call is retried; OpenAI reasoning steps may stay silent longer (30-1800)",
    "gemini_api_key": "Google AI Studio key (LLM, TTS, images, Veo)",
    "openai_api_key": "OpenAI key (LLM, TTS)",
    "openai_model_plan": "OpenAI engine: lecture planning",
    "openai_model_script": "OpenAI engine: scene writing",
    "openai_model_critic": "OpenAI engine: critic / judge",
    "openai_model_fast": "OpenAI engine: small utility calls",
    "anthropic_api_key": "Anthropic key (Claude engine)",
    "anthropic_model_plan": "Claude engine: lecture planning",
    "anthropic_model_script": "Claude engine: scene writing (claude-sonnet-5-5 is a cheaper option)",
    "anthropic_model_critic": "Claude engine: critic / judge (claude-sonnet-5-5 is a cheaper option)",
    "anthropic_model_fast": "Claude engine: small utility calls (claude-sonnet-5-5 is a cheaper option)",
    "tts_provider": "edge is free; fake = deterministic offline audio",
    "elevenlabs_api_key": "ElevenLabs key (TTS with timestamps)",
    "image_provider": "pollinations needs no key (its endpoint may ask for payment: HTTP 402, see IMAGE_FALLBACK_PROVIDERS); none disables generated images",
    "video_provider": "veo generates B-roll within MAX_AI_VIDEOS_PER_LECTURE and the budget",
    "giphy_api_key": "GIPHY key (live-player GIF panels only)",
    "manim_sandbox": "production free-form Manim requires docker",
    "manim_docker_image": "image built from docker/manim-sandbox",
    "manim_allow_freeform": "allow model-written Manim code (else templates only)",
    "manim_visual_qa": "vision-model layout check of rendered animations",
    "render_concurrency": "parallel MP4 segment renders per process",
    "max_cost_per_lecture_usd": "budget per generation job",
    "daily_budget_usd_per_user": "default per-user daily budget",
    "default_language": "default narration language (BCP-47)",
}


def describe(name: str, field: FieldInfo, doc: FieldDoc | None) -> str:
    """One comment line: the description followed by bracketed type hints."""
    text = (doc.comment if doc else "") or EXTRA_DESCRIPTIONS.get(name, "") or (field.description or "")
    hints: list[str] = []
    options = literal_options(field.annotation)
    if options:
        hints.append("options: " + " | ".join(options))
    elif bool in _flatten(field.annotation):
        hints.append("true/false")
    if is_secret(field.annotation):
        hints.append("secret")
    return " ".join([text.rstrip("."), *(f"[{h}]" for h in hints)]).strip()


def render(fields: dict[str, FieldInfo] | None = None, source: str | None = None) -> str:
    """The full .env.example text."""
    fields = fields if fields is not None else dict(config.Settings.model_fields)
    source = source if source is not None else CONFIG_SOURCE.read_text(encoding="utf-8")
    docs = parse_comments(source)
    lines = [HEADER.rstrip("\n")]
    current: str | None = object()  # type: ignore[assignment]  # sentinel: force the first header
    for name, field in fields.items():
        doc = docs.get(name)
        section = doc.section if doc else None
        if section != current:
            current = section
            title = section or "Other"
            lines += ["", f"# --- {title} " + "-" * max(3, 96 - len(title))]
        env = name.upper()
        text = describe(name, field, doc)
        if text:
            lines.append(f"# {text}")
        if is_secret(field.annotation):
            lines.append(f"{env}=")
        else:
            lines.append(f"# {env}={render_value(default_of(field))}")
    lines += ["", COMPOSE_SECTION.rstrip("\n")]
    return "\n".join(lines) + "\n"


def changed(path: Path, text: str) -> bool:
    return not path.is_file() or path.read_text(encoding="utf-8") != text


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is out of date")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(list(argv) if argv is not None else None)
    text = render()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        if changed(args.output, text):
            print(f"{args.output.name} is out of date: run python scripts/gen_env_example.py")
            return 1
        print(f"{args.output.name} is up to date")
        return 0
    with args.output.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
