"""Write ``requirements.lock``: exact pins of the development virtualenv plus Linux-only pins.

    .venv/Scripts/python.exe scripts/lock_requirements.py          # rewrite requirements.lock
    .venv/Scripts/python.exe scripts/lock_requirements.py --check  # exit 1 if the lock drifted

The lock is a pip *constraints* file: it fixes versions but does not decide what is installed.
The Docker image installs only the runtime set; CI and developers add the dev tools:

    pip install -c requirements.lock -r requirements.txt boto3                    # Docker image
    pip install -c requirements.lock -r requirements.txt -r requirements-dev.txt  # CI / development

``pip freeze`` only sees what is installed on the locking machine (Windows). Dependencies that
exist only on Linux, such as ``uvloop`` from ``uvicorn[standard]``, are pinned in ``PLATFORM_PINS``
with environment markers; ``--check`` fails when the Linux dependency closure of requirements.txt
+ requirements-dev.txt needs a package that is neither installed here nor listed there. The project
itself and editable/local installs are excluded. Regenerate after changing requirements.txt /
requirements-dev.txt and re-running the tests.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "requirements.lock"
REQUIREMENT_FILES = (ROOT / "requirements.txt", ROOT / "requirements-dev.txt")
EXTRA_RUNTIME = ("boto3",)  # installed into the Docker image next to requirements.txt (S3/R2 storage)
PROJECT_NAMES = {"aadhi-eduengine", "aadhi_eduengine", "aadhi"}
_PIN_RE = re.compile(r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(\[[^\]]*\])?==(?P<version>\S+)$")


@dataclass(frozen=True)
class PlatformPin:
    """A pin for a dependency that the locking machine's platform never installs."""

    version: str
    marker: str
    reason: str


# Verified on PyPI: uvloop 0.23.0 ships manylinux x86_64/aarch64 wheels for CPython 3.11.
PLATFORM_PINS: dict[str, PlatformPin] = {
    "uvloop": PlatformPin("0.23.0", 'sys_platform != "win32"', "uvicorn[standard] event loop (not on Windows)"),
}

# Environment of the production image / CI runners, used to evaluate dependency markers.
LINUX_ENV: dict[str, str] = {
    "implementation_name": "cpython",
    "implementation_version": "3.11.0",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_release": "",
    "platform_system": "Linux",
    "platform_version": "",
    "python_full_version": "3.11.0",
    "python_version": "3.11",
    "sys_platform": "linux",
}

HEADER = """\
# Exact pins of the development virtualenv (Python 3.11), generated by scripts/lock_requirements.py.
# This is a pip CONSTRAINTS file (it pins versions, requirements files choose what is installed):
#   pip install -c requirements.lock -r requirements.txt boto3                    # Docker image (runtime only)
#   pip install -c requirements.lock -r requirements.txt -r requirements-dev.txt  # CI / development
# Edit requirements.txt / requirements-dev.txt instead, then regenerate.
"""
PLATFORM_HEADER = "# --- platform-specific pins (not installed on the locking machine) ---\n"


def normalise(name: str) -> str:
    """PEP 503 normalised project name."""
    return re.sub(r"[-_.]+", "-", name).lower()


def freeze(python: str = sys.executable) -> list[str]:
    """``pip freeze`` output lines of ``python``'s environment."""
    proc = subprocess.run(
        [python, "-m", "pip", "freeze", "--exclude-editable", "--disable-pip-version-check"],
        capture_output=True,
        text=True,
        timeout=120,
        check=True,
    )
    return proc.stdout.splitlines()


def lock_lines(lines: list[str]) -> list[str]:
    """Keep ``name==version`` pins (sorted, case-insensitive), dropping the project and local paths."""
    pins: dict[str, str] = {}
    for raw in lines:
        line = raw.strip()
        m = _PIN_RE.match(line)
        if not m:
            continue  # comments, "-e", "name @ file:///..." local installs
        if normalise(m.group("name")) in {normalise(n) for n in PROJECT_NAMES}:
            continue
        pins[normalise(m.group("name"))] = f"{m.group('name')}=={m.group('version')}"
    return [pins[k] for k in sorted(pins)]


def platform_lines(pinned: Iterable[str]) -> list[str]:
    """``name==version ; marker`` lines for PLATFORM_PINS that the freeze did not already pin."""
    have = {normalise(p.split("==")[0]) for p in pinned}
    return [f"{name}=={pin.version} ; {pin.marker}" for name, pin in sorted(PLATFORM_PINS.items()) if name not in have]


def render(lines: list[str]) -> str:
    """Full lock file text for ``pip freeze`` output ``lines``."""
    pins = lock_lines(lines)
    extra = platform_lines(pins)
    text = HEADER + "\n".join(pins) + "\n"
    if extra:
        text += PLATFORM_HEADER + "\n".join(extra) + "\n"
    return text


# --- dependency closure ------------------------------------------------------------------------------


def requirement_lines(paths: Iterable[Path] = REQUIREMENT_FILES) -> list[str]:
    """Requirement specifiers from requirements files (comments, blank lines and options skipped)."""
    out: list[str] = []
    for path in paths:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.split(" #", 1)[0].strip()
            if line and not line.startswith(("#", "-")):
                out.append(line)
    return out


def _applies(marker: object | None, env: Mapping[str, str], extras: Iterable[str]) -> bool:
    if marker is None:
        return True
    return any(marker.evaluate({**env, "extra": extra}) for extra in ("", *extras))  # type: ignore[attr-defined]


def linux_closure(roots: Iterable[str], env: Mapping[str, str] = LINUX_ENV) -> tuple[set[str], dict[str, str]]:
    """Walk installed metadata from ``roots`` evaluating markers for ``env``.

    Returns ``(needed, missing)``: normalised names of installed distributions in the closure, and
    ``{name: specifier}`` of requirements that apply under ``env`` but are not installed here.
    """
    from packaging.requirements import Requirement  # dev dependency, only needed for --check

    needed: set[str] = set()
    missing: dict[str, str] = {}
    seen: set[tuple[str, frozenset[str]]] = set()
    stack: list[tuple[Requirement, frozenset[str]]] = [(Requirement(r), frozenset()) for r in roots]
    while stack:
        req, parent_extras = stack.pop()
        if not _applies(req.marker, env, parent_extras):
            continue
        name = normalise(req.name)
        key = (name, frozenset(req.extras))
        if key in seen:
            continue
        seen.add(key)
        try:
            dist = metadata.distribution(req.name)
        except metadata.PackageNotFoundError:
            missing[name] = str(req.specifier)
            continue
        needed.add(name)
        stack.extend((Requirement(dep), frozenset(req.extras)) for dep in dist.requires or [])
    return needed, missing


def platform_gaps() -> list[str]:
    """Problems with PLATFORM_PINS for the Linux closure of the requirements (empty when complete)."""
    from packaging.specifiers import SpecifierSet

    _needed, missing = linux_closure([*requirement_lines(), *EXTRA_RUNTIME])
    problems: list[str] = []
    for name, spec in sorted(missing.items()):
        pin = PLATFORM_PINS.get(name)
        if pin is None:
            problems.append(f"{name}{spec} is needed on Linux but neither installed here nor in PLATFORM_PINS")
        elif not SpecifierSet(spec).contains(pin.version, prereleases=True):
            problems.append(f"PLATFORM_PINS {name}=={pin.version} does not satisfy {name}{spec}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if requirements.lock differs from the venv")
    parser.add_argument("--output", type=Path, default=LOCK)
    args = parser.parse_args(argv)
    lines = freeze()
    text = render(lines)
    gaps = platform_gaps()
    for problem in gaps:
        print(f"error: {problem}")
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current.replace("\r\n", "\n") != text:
            print("requirements.lock differs from the virtualenv: run scripts/lock_requirements.py")
            return 1
        print("requirements.lock matches the virtualenv")
        return 1 if gaps else 0
    with args.output.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {args.output} ({len(lock_lines(lines))} packages + {len(platform_lines(lock_lines(lines)))} platform pins)")
    return 1 if gaps else 0


if __name__ == "__main__":
    sys.exit(main())
