// Copies the pinned third-party browser libraries and fonts from node_modules into web/vendor/
// so the app can run with `script-src 'self'` and the render worker needs no internet access.
// Usage: npm ci && npm run vendor        (web/vendor is generated; do not edit by hand)
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync, readFileSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const nm = join(root, 'node_modules');
const out = join(root, 'web', 'vendor');

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

/** @param {string} from relative to node_modules  @param {string} to relative to web/vendor */
function copy(from, to) {
  const src = join(nm, from);
  if (!existsSync(src)) throw new Error(`missing ${src} — run npm ci`);
  const dst = join(out, to);
  mkdirSync(dirname(dst), { recursive: true });
  cpSync(src, dst, { recursive: true });
}

// --- JavaScript libraries ---------------------------------------------------------------
copy('chart.js/dist/chart.umd.min.js', 'chartjs/chart.umd.min.js');
copy('three/build/three.module.js', 'three/three.module.js');
copy('three/build/three.core.js', 'three/three.core.js');
copy('mathjs/lib/browser/math.js', 'mathjs/math.js');
copy('p5/lib/p5.min.js', 'p5/p5.min.js');
copy('dompurify/dist/purify.min.js', 'dompurify/purify.min.js');
copy('marked/lib/marked.umd.js', 'marked/marked.umd.js');
copy('prismjs/prism.js', 'prism/prism.js');
for (const lang of ['python', 'c', 'cpp', 'java', 'javascript', 'clike', 'markup', 'bash', 'sql', 'matlab', 'verilog']) {
  copy(`prismjs/components/prism-${lang}.min.js`, `prism/components/prism-${lang}.min.js`);
}
copy('prismjs/themes/prism-tomorrow.css', 'prism/prism-tomorrow.css');

// MathJax: SVG output bundle + the extensions it may autoload + ui/safe (html/bbox/unicode
// autoloads are disabled in web/js/shared/libs.js).
copy('mathjax/es5/tex-svg.js', 'mathjax/tex-svg.js');
copy('mathjax/es5/ui/safe.js', 'mathjax/ui/safe.js');
copy('mathjax/es5/input/tex/extensions', 'mathjax/input/tex/extensions');
for (const banned of ['html.js', 'bbox.js', 'unicode.js', 'require.js']) {
  rmSync(join(out, 'mathjax/input/tex/extensions', banned), { force: true });
}

// --- Fonts (latin + Indic scripts), font-display: block for deterministic renders ----------
const FONTS = [
  { pkg: 'inter', family: 'Inter', weights: [300, 400, 600, 700] },
  { pkg: 'outfit', family: 'Outfit', weights: [300, 400, 700, 900] },
  { pkg: 'jetbrains-mono', family: 'JetBrains Mono', weights: [400, 700] },
  { pkg: 'noto-sans-tamil', family: 'Noto Sans Tamil', weights: [400, 700] },
  { pkg: 'noto-sans-devanagari', family: 'Noto Sans Devanagari', weights: [400, 700] },
  { pkg: 'noto-sans-telugu', family: 'Noto Sans Telugu', weights: [400, 700] },
  { pkg: 'noto-sans-kannada', family: 'Noto Sans Kannada', weights: [400, 700] },
  { pkg: 'noto-sans-malayalam', family: 'Noto Sans Malayalam', weights: [400, 700] },
];
let css = '/* Generated by scripts/vendor.mjs — self-hosted fonts (font-display: block). */\n';
for (const f of FONTS) {
  const filesDir = join(nm, '@fontsource', f.pkg, 'files');
  const files = readdirSync(filesDir).filter((n) => n.endsWith('-normal.woff2'));
  for (const weight of f.weights) {
    for (const file of files.filter((n) => n.includes(`-${weight}-normal.woff2`))) {
      // subset is the part between the package name and the weight, e.g. "latin", "tamil", "latin-ext"
      const subset = file.slice(f.pkg.length + 1, file.length - `-${weight}-normal.woff2`.length);
      if (!['latin', 'latin-ext', 'tamil', 'devanagari', 'telugu', 'kannada', 'malayalam'].includes(subset)) continue;
      copy(`@fontsource/${f.pkg}/files/${file}`, `fonts/${file}`);
      const range = unicodeRange(subset);
      css += `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${weight};font-display:block;` +
        `src:url('./fonts/${file}') format('woff2');${range ? `unicode-range:${range};` : ''}}\n`;
    }
  }
}
writeFileSync(join(out, 'fonts.css'), css);

function unicodeRange(subset) {
  return {
    latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
    'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
    tamil: 'U+0964-0965,U+0B82-0BFA,U+200C-200D,U+20B9,U+25CC',
    devanagari: 'U+0900-097F,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,U+25CC,U+A830-A839,U+A8E0-A8FF,U+11B00-11B09',
    telugu: 'U+0951-0952,U+0964-0965,U+0C00-0C7F,U+1CDA,U+1CF2,U+200C-200D,U+25CC',
    kannada: 'U+0951-0952,U+0964-0965,U+0C80-0CF3,U+1CD0,U+1CD2-1CD3,U+1CDA,U+1CF2,U+1CF4,U+200C-200D,U+20B9,U+25CC,U+A830-A835',
    malayalam: 'U+0307,U+0323,U+0951-0952,U+0964-0965,U+0D00-0D7F,U+1CDA,U+1CF2,U+200C-200D,U+20B9,U+25CC',
  }[subset];
}

// --- manifest with sha384 integrity of every JS file -------------------------------------
const manifest = {};
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (name.endsWith('.js')) {
      const rel = p.slice(out.length + 1).replaceAll('\\', '/');
      manifest[rel] = 'sha384-' + createHash('sha384').update(readFileSync(p)).digest('base64');
    }
  }
})(out);
writeFileSync(join(out, 'manifest.json'), JSON.stringify(manifest, null, 1));
console.log(`vendored ${Object.keys(manifest).length} scripts + fonts into web/vendor`);
